### PR TITLE
fix(title): fix copying on WSL 2 by bumping clipboardy version

### PR DESCRIPTION
**Pull request by bryan-hoang**
## Commit message

In [this PR](https://github.com/sindresorhus/clipboardy/pull/59), support for WSL was added in `clipboardy` v2.3.0. Since WSL
support for `title` would be nice, `clipboardy`'s version was increased
from 1.2.2 to 3.0.0.

Because `clipboardy` is now an ES module, the method of importing it had
to change to use the `import` function rather than `require`.

## Additional information

After testing locally in WSl 2, I've confirmed that the changes does enable auto-copying on WSL to function as described. When I ran the tests, they all passed. Albeit, it was on Node `v17.0.1`.

There is no `engines` field in the `package.json` file specifying the node version, so I'm unsure if this PR would count as a breaking change to using `import`.

Please let me know of any changes I should make!

### CODE REVIEW

**Comment by bryan-hoang** [comment]
> Are you interested in tackling #69?

After reading through the ticket and the linked gist, I would say I'm interested to trying to address it!

**Comment by leerob** [comment]
Awesome, yeah I figured I'd mention that since it's related to this PR.

**Review by vaudy — APPROVED** [review]

**Comment by vaudy** [comment]
it would be nice to have this fix since it also fix vulnerabilities issue for using exec 0.8.0

**Comment by bryan-hoang** [comment]
It looks like project now uses `pnpm` to manage the dependencies, making this PR obsolete. I do want to take a stab at #69 like I promised to, so I'll close this PR and reopen another one that aims to address #69 as well as the dependency issue for `clipboardy`.

**Comment by bryan-hoang** [comment]
#83 includes updating `clipboardy` to v3.0.0.

**Pull request closed without merging**
