### PR TITLE
Add "GraphQL" to specials.js

### PR DESCRIPTION
**Pull request by mxstbr**

### CODE REVIEW

**Review by leerob — APPROVED** [review]
🔥

**Comment by leerob** [comment]
Shipped https://github.com/vercel/title/releases/tag/3.5.0

**Comment by mxstbr** [comment]
Amazing, thank you @leerob! When can I expect the update to be live on https://title.sh? (which is what I use almost every day, thank you for the fantastic tool 🙇 )

CleanShot 2022-08-09 at 17 55 50

**Comment by leerob** [comment]
Done! https://github.com/vercel/title-site/pull/40

**Pull request merged**
